### ISSUE TITLE
[2] As a User, I want to be able to login on my account so that I have access to my profile information

### ISSUE THREAD

**Issue by deborahlago** [FEUP-ESOF-2020-21/open-cx-t3g2-codynamics#15]
As a User, I want to be able to login on my account so that I have access to my profile information.

Checklist:
- [x] FrontEnd
- [x] Tests
- [x] Documentation
- [x] BackEnd

Effort: 
2

Priority:
3

**Comment by joaofbrandao** [comment]
Scenario: login in the app
    Given a user that has the app
    When I tap the "login" button
    And I insert my data
    Then i am redirected to the homepage

**Comment by joaofbrandao** [comment]
Before Login:
![Screenshot from 2020-12-04 02-51-08](https://user-images.githubusercontent.com/36771351/101119166-a7430380-35e2-11eb-812b-68fbb4315ba5.png)

**Comment by joaofbrandao** [comment]
After Login:
![Screenshot from 2020-12-04 03-42-21](https://user-images.githubusercontent.com/36771351/101119255-db1e2900-35e2-11eb-9c18-29444bd4d04a.png)
