### ISSUE TITLE
[2] As a User, I want to be able to logout from my account.

### ISSUE THREAD

**Issue by deborahlago** [FEUP-ESOF-2020-21/open-cx-t3g2-codynamics#16]
As a User, I want to be able to logout from my account.

Checklist:
- [x] FrontEnd
- [x] Tests
- [x] Documentation
- [x] BackEnd

Effort: 
2

Priority:
3

**Comment by joaofbrandao** [comment]
Acceptance Test:

    Scenario: logout from the app
    Given an user that is logged in
    When I click the "logout" button
    Then I go back to the "login" page

**Comment by joaofbrandao** [comment]
Before Logout: 
![Screenshot from 2020-12-04 02-51-03](https://user-images.githubusercontent.com/36771351/101118274-a4dfaa00-35e0-11eb-92e4-1a4c71c3625c.png)

**Comment by joaofbrandao** [comment]
After Logout:
![Screenshot from 2020-12-04 02-51-08](https://user-images.githubusercontent.com/36771351/101118299-af9a3f00-35e0-11eb-8afc-0fc457cace5c.png)
