### ISSUE TITLE
Investigar Flutter e Android Studio

### ISSUE THREAD

**Issue by ghost** [FEUP-ESOF-2020-21/open-cx-t3g2-codynamics#8]
Investigar Flutter e Android Studio para ver como funciona

**Comment by raulviana** [comment]
Entre intelliJ e android studio (AS) será preferível utilizar AS, pois é um IDE vocacionado para o desenvolvimento mobile. Para além disso para adiocionar suporte ao Flutter basta ir a settings -> plugIns e adicionar o plugIn Flutter.
Em relação ao projeto, e pelo que vi na lista do ano passado, existe um projeto parecido, que podemos tentar melhorar adicionando a feature speed meeeting. É o número 55 da equipa power Rangers e já tem matches implementados. Podíamos trabalhar em cima disso e implementar as reuniões por cima desse match que já está feito..
